[tool.poetry]
name = "opensearch-logger"
version = "0.1.0"

authors = ["vduseev <vagiz@duseev.com>", "IMInterne <equipe_interne@innovmetric.com>"]
maintainers = ["vduseev <vagiz@duseev.com>"]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Topic :: System :: Logging",
  "Topic :: Software Development :: Libraries",
  "Topic :: Internet :: Log Analysis",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3.8",
]
description = "OpenSearch logging handler"
keywords = ["opensearch", "logging", "handler", "logger"]

documentation = "https://github.com/vduseev/python-opensearch-logger"
homepage = "https://github.com/vduseev/python-opensearch-logger"
repository = "https://github.com/vduseev/python-opensearch-logger"

license = "Apache-2.0"
readme = "README.md"

packages = [
  {include = "opensearch_logger"},
]

[tool.poetry.dependencies]
opensearch-py = "^1.0.0"
python = "^3.8"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
black = "^21.10b0"
bump2version = "^1.0.1"
ipython = "^7.29.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
