name: Test
on:
  pull_request: {}
  push: {}
  workflow_dispatch: {}

jobs:
  run-tests:
    name: Run tests

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up poetry
        uses: abatilo/actions-poetry@v2.0.0

      - name: Install project dependencies
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install -vvv

      - name: Pull latest Opensearch image
        run: |
          docker pull opensearchproject/opensearch:latest
        if: ${{ runner.os == "Linux" }}

      - name: Start Opensearch container
        run: |
          docker run -d --rm \
            --name opensearch \
            -e "cluster.name=opensearch-cluster" \
            -e "node.name=opensearch" \
            -e "discovery.type=single-node" \
            -e "bootstrap.memory_lock=true" \
            -p "9200:9200" \
            opensearchproject/opensearch:latest
        if: ${{ runner.os == "Linux" }}

      - name: Stop Opensearch container
        run: |
          docker stop --time 3 opensearch
        if: ${{ runner.os == "Linux" }}
